### ISSUE TITLE
Adding MemBlock

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_extras#17]
I want to add Xuan's MemBlock network (the thing that was kind of like a flip-flop) that he used in his Master's Thesis to this repository. Is it okay to add a `networks.py` file and just shove everything in there?

**Comment by hunse** [comment]
Is it a SPA component or just a normal network? If it's SPA, I would make a `spa` directory and make a file in there. If it's a network, I would make a `networks` directory and put it in there.

**Comment by xchoo** [comment]
It can be both, depending on what is done to configure it. For example, in Spaun's repo, there are two versions: the [network version](https://github.com/xchoo/spaun2.0/blob/master/_spaun/_networks/mem_block_basic.py), and the [SPA version](https://github.com/xchoo/spaun2.0/blob/master/_spaun/_spa/mem_block.py).
Granted the SPA version is more complex (supports more features), but they are essentially the same thing. Note: The network version needs some updating to new nengo code standards.

**Comment by hunse** [comment]
We now have a `networks` directory and a `spa` one, so either (or both), depending on if you're adding the network version or the SPA version as @xchoo described.
