### ISSUE TITLE
Make pip release

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_extras#63]
A pip release would make it easier to declare `nengo_extras` as a dependcy in other projects/models. Currently, it has to be included as dependency link which requires the additional option `--process-dependency-links` to `pip`. Furthermore, this option has been deprecated and will be removed in a future `pip` release.

**Comment by tbekolay** [comment]
[Done](https://pypi.org/project/nengo-extras/)

**Comment by tbekolay** [comment]
Hm... I'm not sure why the package name had its underscore replaced by a hyphen... it's either `twine` or the new PyPI infrastructure they have. If you grep this repo you will see no instances of `nengo-extras`, it's always `nengo_extras`, so I'll see if that's something that can be changed or if we're stuck with it. In any case, both `pip install nengo-extras` and `pip install nengo_extras` works.

**Comment by tbekolay** [comment]
I've done some digging and it seems like it might be possible, but not straightforward to change the PyPI package name ... and even if we do, it seems like there's a push within the Python community to switch to using hyphens and not underscores in package names. Please see [this forum post](https://forum.nengo.ai/t/python-package-names-nengo-x-versus-nengo-x/487) which has more details and a poll for how to move forward.
